# Generated by Django 4.1.4 on 2023-09-06 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название услуги')),
                ('description', models.TextField(verbose_name='Описание услуги')),
                ('price', models.IntegerField(verbose_name='Стоимость услуги')),
                ('size', models.IntegerField(verbose_name='Стоимость услуги')),
            ],
            options={
                'verbose_name': 'Услуги',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='MealType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Категория')),
                ('image', models.ImageField(upload_to='meal_types/', verbose_name='Изображение')),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='MealClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_date', models.DateTimeField(verbose_name='Дата клика')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cafe_core_app.meal')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_type', to='cafe_core_app.mealtype', verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='ImageMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='meal_images/', verbose_name='Изображение')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cafe_core_app.meal')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
