# Generated by Django 4.1.4 on 2023-09-06 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_core_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Единственное число названия модели',
                'verbose_name_plural': 'Название модели',
            },
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='meal_type', to='cafe_core_app.mealtype', verbose_name='Категория'),
        ),
    ]
