# Generated by Django 4.1.4 on 2023-09-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_core_app', '0002_yourmodel_alter_meal_meal_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YourModel',
        ),
        migrations.AlterField(
            model_name='meal',
            name='price',
            field=models.FloatField(verbose_name='Стоимость услуги'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='size',
            field=models.FloatField(verbose_name='Стоимость услуги'),
        ),
    ]
