# Generated by Django 4.1.4 on 2023-09-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_core_app', '0003_delete_yourmodel_alter_meal_price_alter_meal_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='price',
            field=models.CharField(max_length=10, verbose_name='Стоимость услуги'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='size',
            field=models.CharField(max_length=10, verbose_name='Стоимость услуги'),
        ),
    ]
