# Generated by Django 4.1.4 on 2023-09-08 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_core_app', '0004_alter_meal_price_alter_meal_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название услуги'),
        ),
        migrations.AlterField(
            model_name='mealtype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Категория'),
        ),
    ]
